# Generated by Django 5.1.4 on 2025-01-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_or_email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
