# Generated by Django 5.1.4 on 2025-01-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_confirmation_code_user_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
    ]
