# Generated by Django 5.1.4 on 2025-01-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('price_of_1_kwork', models.IntegerField(choices=[(1, '$1'), (4, '$4'), (7, '$7'), (10, '$10'), (13, '$13'), (16, '$16'), (19, '$19'), (22, '$22'), (25, '$25'), (28, '$28'), (31, '$31'), (34, '$34'), (37, '$37'), (40, '$40'), (43, '$43'), (46, '$46'), (49, '$49'), (52, '$52'), (55, '$55'), (58, '$58'), (61, '$61'), (64, '$64'), (67, '$67'), (70, '$70'), (73, '$73'), (76, '$76'), (79, '$79'), (82, '$82'), (85, '$85'), (88, '$88'), (91, '$91'), (94, '$94'), (97, '$97'), (100, '$100'), (103, '$103'), (106, '$106'), (109, '$109'), (112, '$112'), (115, '$115'), (118, '$118'), (121, '$121'), (124, '$124'), (127, '$127'), (130, '$130'), (133, '$133'), (136, '$136'), (139, '$139'), (142, '$142'), (145, '$145'), (148, '$148'), (151, '$151'), (154, '$154'), (157, '$157'), (160, '$160'), (163, '$163'), (166, '$166'), (169, '$169'), (172, '$172'), (175, '$175'), (178, '$178'), (181, '$181'), (184, '$184'), (187, '$187'), (190, '$190'), (193, '$193'), (196, '$196'), (199, '$199'), (202, '$202'), (205, '$205'), (208, '$208'), (211, '$211'), (214, '$214'), (217, '$217'), (220, '$220'), (223, '$223'), (226, '$226'), (229, '$229'), (232, '$232'), (235, '$235'), (238, '$238')], default='$1')),
                ('delivery', models.IntegerField(choices=[(0, '0 days'), (1, '1 days'), (2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days'), (8, '8 days'), (9, '9 days'), (10, '10 days')], default='0 days')),
                ('description', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequently_Asked_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=80)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='2_project/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.category')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('country', models.CharField(max_length=250)),
                ('about', models.TextField()),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('name', models.CharField(max_length=250)),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=100, max_digits=100)),
                ('deadline', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Prices_and_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_this_kwork', models.CharField(max_length=250)),
                ('price_of_1_kwork', models.IntegerField(choices=[(8, '$8'), (16, '$16'), (24, '$24'), (32, '$32'), (40, '$40'), (48, '$48'), (56, '$56'), (64, '$64'), (72, '$72'), (80, '$80'), (88, '$88'), (96, '$96'), (104, '$104'), (112, '$112'), (120, '$120'), (128, '$128'), (136, '$136'), (144, '$144'), (152, '$152'), (160, '$160'), (168, '$168'), (176, '$176'), (184, '$184'), (192, '$192'), (200, '$200'), (208, '$208'), (216, '$216'), (224, '$224'), (232, '$232'), (240, '$240'), (248, '$248'), (256, '$256'), (264, '$264'), (272, '$272'), (280, '$280'), (288, '$288'), (296, '$296')], default='$8')),
                ('delivery', models.IntegerField(choices=[(1, '1 days'), (2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days'), (8, '8 days'), (9, '9 days'), (10, '10 days'), (11, '11 days'), (12, '12 days'), (13, '13 days'), (14, '14 days'), (15, '15 days'), (16, '16 days'), (17, '17 days'), (18, '18 days'), (19, '19 days'), (20, '20 days'), (21, '21 days'), (22, '22 days'), (23, '23 days'), (24, '24 days'), (25, '25 days'), (26, '26 days'), (27, '27 days'), (28, '28 days'), (29, '29 days'), (30, '30 days')], default='1 days')),
                ('extra_options', models.ManyToManyField(related_name='options', to='common.extra_options')),
            ],
        ),
        migrations.CreateModel(
            name='Kwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='kwork_image/')),
                ('description', models.TextField()),
                ('order_requirements', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('body', models.TextField()),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.comment')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='PortfolioPriceOption',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('option', models.CharField(max_length=200)),
                ('portfolio_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.portfolioprice')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller'),
        ),
        migrations.CreateModel(
            name='SellerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.seller')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.skill')),
            ],
        ),
    ]
