# Generated by Django 5.1.4 on 2025-01-07 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('price_of_1_kwork', models.IntegerField(choices=[(1, '1'), (4, '4'), (7, '7'), (10, '10'), (13, '13'), (16, '16'), (19, '19'), (22, '22'), (25, '25'), (28, '28'), (31, '31'), (34, '34'), (37, '37'), (40, '40'), (43, '43'), (46, '46'), (49, '49'), (52, '52'), (55, '55'), (58, '58'), (61, '61'), (64, '64'), (67, '67'), (70, '70'), (73, '73'), (76, '76'), (79, '79'), (82, '82'), (85, '85'), (88, '88'), (91, '91'), (94, '94'), (97, '97'), (100, '100'), (103, '103'), (106, '106'), (109, '109'), (112, '112'), (115, '115'), (118, '118'), (121, '121'), (124, '124'), (127, '127'), (130, '130'), (133, '133'), (136, '136'), (139, '139'), (142, '142'), (145, '145'), (148, '148'), (151, '151'), (154, '154'), (157, '157'), (160, '160'), (163, '163'), (166, '166'), (169, '169'), (172, '172'), (175, '175'), (178, '178'), (181, '181'), (184, '184'), (187, '187'), (190, '190'), (193, '193'), (196, '196'), (199, '199'), (202, '202'), (205, '205'), (208, '208'), (211, '211'), (214, '214'), (217, '217'), (220, '220'), (223, '223'), (226, '226'), (229, '229'), (232, '232'), (235, '235'), (238, '238')], default=1)),
                ('delivery', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
                ('description', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('country', models.CharField(max_length=250)),
                ('about', models.TextField()),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('name', models.CharField(max_length=250)),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='OneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('select_category', models.ManyToManyField(related_name='categories', to='common.category_select')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('kwork_cover_image', models.ImageField(null=True, upload_to='kwork_image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.onecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=100, max_digits=100)),
                ('deadline', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Prices_and_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_this_kwork', models.CharField(max_length=250)),
                ('price_of_1_kwork', models.IntegerField(choices=[(8, '8'), (16, '16'), (24, '24'), (32, '32'), (40, '40'), (48, '48'), (56, '56'), (64, '64'), (72, '72'), (80, '80'), (88, '88'), (96, '96'), (104, '104'), (112, '112'), (120, '120'), (128, '128'), (136, '136'), (144, '144'), (152, '152'), (160, '160'), (168, '168'), (176, '176'), (184, '184'), (192, '192'), (200, '200'), (208, '208'), (216, '216'), (224, '224'), (232, '232'), (240, '240'), (248, '248'), (256, '256'), (264, '264'), (272, '272'), (280, '280'), (288, '288'), (296, '296')], default=8)),
                ('delivery', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=1)),
                ('extra_options', models.ManyToManyField(related_name='options', to='common.extra_options')),
            ],
        ),
        migrations.AddField(
            model_name='category_select',
            name='add_type_of_services',
            field=models.ManyToManyField(related_name='services', to='common.typeofservice'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='2_project/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.category')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('body', models.TextField()),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.comment')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='PortfolioPriceOption',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('option', models.CharField(max_length=200)),
                ('portfolio_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.portfolioprice')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller'),
        ),
        migrations.CreateModel(
            name='SellerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.seller')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.skill')),
            ],
        ),
    ]
