# Generated by Django 5.1.4 on 2025-01-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_attach_files_alter_extra_options_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequently_Asked_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=80)),
                ('answer', models.TextField()),
            ],
        ),
    ]
