# Generated by Django 5.1.4 on 2025-01-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_or_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_or_email',
        ),
    ]
