# Generated by Django 5.1.4 on 2025-01-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_auth_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_status',
        ),
    ]
