# Generated by Django 5.1.4 on 2025-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=20),
        ),
    ]
